jobs:
  include:
    - stage: "test js"
      language: node_js
      node_js: node

    - stage: "build example"
      language: android
      jdk: oraclejdk8
      android:
        components:
          - build-tools-23.0.1
          - android-23
          - extra-android-m2repository
          - extra-android-support
      script:
        - nvm install node
        - cd example
        - npm i
        - cd android
        - ./gradlew assembleDebug
        - ./gradlew assembleRelease
        - ls -l app/build/outputs/apk

    - stage: "build example"
      language: objective-c
      osx_image: xcode9.1
      script:
        - nvm install node
        - cd example
        - npm i
        - cd ios
        - pod install
        - xcodebuild -workspace RNAMap3D.xcworkspace -scheme RNAMap3D -sdk iphonesimulator -quiet

cache:
  directories:
    - node_modules
    - example/node_modules
    - ~/.gradle/caches
    - ~/.gradle/wrappers
    - ~/.rncache
    - ~/Library/Caches/CocoaPods/Pods/
