aliases:
  - &android
    components:
      - build-tools-28.0.3
      - android-28
      - extra-android-m2repository
      - extra-android-support
  
  - &android-cache
    directories:
      - ~/.cache/yarn
      - ~/.gradle/caches/modules-2
      - ~/.gradle/wrapper
  
  - &ios-cache
    directories:
      - ~/.rncache
      - ~/Library/Caches/Yarn
      - ~/Library/Caches/CocoaPods

  - &init-new-project
    |
      nvm install node
      yarn global add react-native-cli
      react-native init App --version="0.58.4"
      cd App
      yarn add react-native-amap3d@next

jobs:
  include:
    - stage: "build test for example"
      language: android
      jdk: oraclejdk8
      android: *android
      before_cache:
        - rm ~/.gradle/caches/modules-2/modules-2.lock
      cache: *android-cache
      script:
        - nvm install node
        - yarn
        - yarn build
        - cd android
        - TERM=dumb ./gradlew build
        - ls -lh app/build/outputs/apk/debug
        - ls -lh app/build/outputs/apk/release

#    - stage: "build test for example"
#      language: objective-c
#      osx_image: xcode10.1
#      cache: *ios-cache
#      script:
#        - nvm install node
#        - brew install yarn
#        - yarn
#        - cd ios
#        - pod install --repo-update
#        - xcodebuild -workspace RNAMap3D.xcworkspace -scheme RNAMap3D -sdk iphonesimulator -quiet

stages:
  - name: "build test for example"
#    if: branch = master
  - name: "build test for new project"
    if: branch = release
