name: build-docs
on:
  push:
    branches: [main]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: npm i typescript typedoc
      - run: npx typedoc --out docs/api --skipErrorChecking src
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
