name: build
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm pack
      - run: npx react-native init example
        working-directory: ../
      - run: cp index.js ../example/
      - run: cp -r example ../example/
      - run: npm i ../react-native-amap3d/react-native-amap3d-0.0.0.tgz
        working-directory: ../example
      - run: npm i @react-native-picker/picker @react-navigation/native @react-navigation/native-stack react-native-safe-area-context react-native-screens
        working-directory: ../example
      - run: sed -i.backup -r 's/(enableSeparateBuildPerCPUArchitecture = )false/\1true/' build.gradle
        working-directory: ../example/android/app
      - run: ./gradlew assembleRelease
        working-directory: ../example/android
      - uses: bruceadams/get-release@v1.2.3
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"
      - run: npm version ${{ steps.release.outputs.tag_name }} --no-git-tag-version
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ../example/android/app/build/outputs/apk/release/app-arm64-v8a-release.apk
          asset_name: example.apk
          asset_content_type: application/vnd.android.package-archive
