name: release
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: bruceadams/get-release@v1.3.2
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
      - run: npm version ${{ steps.release.outputs.tag_name }} --no-git-tag-version
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  build-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm pack
      - run: npx react-native init example
      - run: cp index.js example/
      - run: cp -r example-app example/
      - run: npm i ../react-native-amap3d-0.0.0.tgz
        working-directory: example
      - run: npm i @react-native-picker/picker @react-navigation/native @react-navigation/native-stack react-native-safe-area-context react-native-screens
        working-directory: example
      - run: sed -i.backup -r 's/(enableSeparateBuildPerCPUArchitecture = )false/\1true/' build.gradle
        working-directory: example/android/app
      - run: ./gradlew assembleRelease
        working-directory: example/android
      - uses: svenstaro/upload-release-action@v2
        with:
          file: example/android/app/build/outputs/apk/release/app-*-release.apk
          file_glob: true
